name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/student-registration-system:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # LIGHTSAIL DEPLOYMENT STEP'İ EKLENDİ
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Lightsail region'ınız

    - name: Deploy to Lightsail
      run: |
        aws lightsail create-container-service-deployment \
          --service-name student-registration-system-service \
          --containers '{
                          "student-registration-system": {
                "image": "${{ secrets.DOCKERHUB_USERNAME }}/student-registration-system:latest",
              "ports": {
                "5000": "HTTP"
              },
              "environment": {
                "SECRET_KEY": "${{ secrets.SECRET_KEY }}",
                "DATABASE_URL": "${{ secrets.DATABASE_URL }}",
                "MAIL_USERNAME": "${{ secrets.MAIL_USERNAME }}",
                "MAIL_PASSWORD": "${{ secrets.MAIL_PASSWORD }}",
                "MAIL_DEFAULT_SENDER": "${{ secrets.MAIL_DEFAULT_SENDER }}"
              }
            }
          }' \
          --public-endpoint '{
                            "containerName": "student-registration-system",
            "containerPort": 5000
          }'
